### ISSUE TITLE
Custom error message 

### ISSUE THREAD

**Issue by deepak191093** [santhosh-tekuri/jsonschema#96] opened 2022-12-15 05:40 UTC
I want to return custom error message not predefined as it is not understandable to common people.

**Comment by santhosh-tekuri** [comment] 2022-12-23 06:11
can you please elaborate what do you mean by that. may be giving an example would be better

**Comment by santhosh-tekuri** [comment] 2023-01-09 22:52
Started working on this feature. Will post pull request tomarrow

**Comment by deepak191093** [comment] 2023-01-11 06:07
looking forward to it.

**Comment by santhosh-tekuri** [comment] 2023-01-11 06:28
please check pull request #99
this pull request changes type of ValidationError.Message from string to struct implementing fmt.Stringer

go through the changes and let me know your opinion

**Comment by santhosh-tekuri** [comment] 2023-01-12 11:19
closing. seems duplicate of #44

**Closed by santhosh-tekuri** 2023-01-12 11:19 UTC
Labels: duplicate

**Comment by deepak191093** [comment] 2023-01-12 11:26
i am using for json schema validation with 2020-12 draft. to send custom message which field should i mention in json schema file. Need a clarification on that.

**Comment by santhosh-tekuri** [comment] 2023-01-12 11:42
@deepak191093 it is still work in progress. see issue #44 and PR #99

since this is a breaking change I have to bump the version. I am waiting for your opinion before I can release it

**Comment by santhosh-tekuri** [comment] 2023-01-12 13:26
fix is available in `v6.0.0-alpha.1`

**Comment by deepak191093** [comment] 2023-01-18 11:14
hey, can you please update the document of explain a sample here hot it works.
i am using json schema 2020-12 draft how can i send custom error messages ?
it would be really helpful

**Comment by santhosh-tekuri** [comment] 2023-01-18 14:45
`ValidationError.Message` was `string` type. now it is changed to `fmt.Stringer`.  
so you can create custom error message as follows:

```go
import (
	"github.com/santhosh-tekuri/jsonschema/v5"
	"github.com/santhosh-tekuri/jsonschema/v5/msg"
)

func getCustomMessage(err *jsonschema.ValidationError) string {
	switch m := err.Message.(type) {
	case msg.Type:
		return fmt.Sprintf("i am expecting %s, but I got %s", m.Want, m.Got)
	default:
		return err.Message.String()
	}
}
```

the above code shows how to create custom error message for type mismatch. similarly you can add more cases in switch for customising different error messages. see `msg` subpackage for different error message structs.
